### PR TITLE
dbdump: new way of dumping

### LINKED ISSUE #8: Refactor dbdump
The dbdump script isn't working correctly (again). Refactor and add some checks before persisting the dump.

### PR DESCRIPTION
**Pull request by Lodifice**
The flag that states whether a user is a teacher is needed by the OKR project. As it is stored as a `user_field`, we have to stop ignoring the `user_field` table in the dump.

With the current change, all contents of `user_field` are dumped, which is probably not wanted. There are two options:

1. Continue the current approach of the dump script and remove the superfluously dumped data with sed magic.
2. Ignore `user_field` in the main dump and add a separate query.

Do you have any opinion and would you mind implementing this change?

Fixes #8

### CODE REVIEW

**Comment by Knorrke** [comment]
From discussion with @inyono: The dump is only used for testing, so it should not need the real data? We probably could randomize the needed data in the user field table.

**Comment by Lodifice** [comment]
Instead of dumping all tables and then attempting to anonymize `user` with a sed script, we now only write selected columns of `user` into a CSV file.

**Comment by inyono** [comment]
This doesn't dump the whole database anymore, or am I missing something? We kinda need that behavior though, so that we can reuse the dumps in dev & staging; and locally.

**Comment by Lodifice** [comment]
What else are the dumps needed for?

Feel free to add any table you want in the dump, but the plan was to have a whitelist rather than a blacklist so that we don't accidentally dump data that should not be dumped.

**Comment by inyono** [comment]
Pretty much what I said above:
- They are used to hydrate the database in the dev & staging cluster
- They can be downloaded by devs to get current production data into their local environment

For both of these use cases, we need a complete dump (except the data in the sessions table, so pretty much the same logic we had before). Apart from the user table, everything is fine to dump since it is public accessible in some way anyways (e.g. all events triggered by me: https://de.serlo.org/event/history/user/15473). Of course: when we add additional data to the database in the future, we need to check whether we need to remove/anonymise them.

**Comment by Lodifice** [comment]
The complete dump is in place now, I prefer a whitelist to a blacklist in order to not accidentally dump something we don't want to dump. However, I also see arguments for a blacklist.

**Pull request merged**
